### ISSUE TITLE
Double-check docker_compose_path order

### ISSUE THREAD

**Issue by ahmadia** [memex-explorer/memex-explorer#494]
In models.py

I don't understand why we're mucking with the PATH here, this seems fragile and likely to break things.  @amfarrell - do we still need this code?

**Comment by amfarrell** [comment]
When I installed docker-compose as a python package and then ran it under sudo (as you need to do if you don't implement https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access), It could not find docker-compose because miniconda the path is reset when you run commands under sudo. The answer is to either:
1) install docker-compose into some place already in the secure_path found in /etc/sudoers
2) run the docker client as a non-root user. (see https://docs.docker.com/installation/binaries/#giving-non-root-access)
3) continue to refer to the particular binary.

I suspect that #2 is the right choice.

**Comment by ahmadia** [comment]
4) - Set the PATH on the sudo calls: `sudo env "PATH=$PATH"`

**Comment by ahmadia** [comment]
Alright, let's get this fixed.  I'm okay with 1, 2, or 4.

**Comment by brittainhard** [comment]
No longer relevant.
