### ISSUE TITLE
404 error when running on DigitalOcean

### ISSUE THREAD

**Issue by geoffwalmsley** [memex-explorer/memex-explorer#715]
Spun up a Digital Ocean instance: Ubuntu 14.04 with Docker preinstalled and 4GB ram.

From cmd line executed:

sudo docker run -d -p 80:5000 --name memex continuumio/memex_explorer

and docker ps shows it is running.

When I navigate to the IP address of the instance it throws a 404 error: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by ahmadia** [comment]
Thanks for the report @geoffwalmsley.  I'll be fixing up the Docker deploy next week, can this wait until Monday?

**Comment by geoffwalmsley** [comment]
It sure can...many thanks

**Comment by ahmadia** [comment]
@geoffwalmsley - I took a spin at this and noticed there was a problem with our documentation.  Unfortunately we've got two Docker repositories, memex_explorer and memex-explorer.

Can you try:

```
docker pull continuumio/memex-explorer:v0.2-demo
sudo docker run -d -p 80:8000 --name memex continuumio/memex_explorer
```

Then head to the URL of your server?  

This isn't a completely functional Memex Explorer (some applications are only loosely coupled to the Docker image).  Is there a specific piece of functionality you were interested in checking out?

**Comment by geoffwalmsley** [comment]
Thanks, that worked.

I would be most interested in the data vis and trying out both nutch and ache crawls. Unfortunately though. the visualization isn't working with this config.

**Comment by ahmadia** [comment]
With regards to data visualization, there should be some automatic visualization that runs with Ache crawls (backed by Bokeh plots).  We've mostly been leveraging Kibana visualizations to look at crawl data, but we haven't really built up any dashboards since the best visualizations tend to be domain-specific.  

We've got some work on providing real-time visualization of the Nutch crawler: https://github.com/memex-explorer/memex-explorer/pull/720

But this is still very much embryonic work.

We're also improving our interoperability with DDT, which provides a nice visualization of the domain discovery process, which is a pre-crawl procedure for identifying a good crawl model and seed list.

**Comment by ahmadia** [comment]
You should definitely be able to run nutch/ache crawls from that Docker image, be mindful of your disk/network, as both crawlers will aggressively use up both even for "small" crawls.

**Comment by ahmadia** [comment]
I'm going to close this for now, but feel free to continue the discussion or raise new issues.  We appreciate the feedback :)
